input: classpath:users.csv
server:
  port: 8092
spring:
  batch:
    job:
      enabled: false
    initialize-schema: ALWAYS
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/batchDB?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update